[tool.black]
line-length = 119
target-version = ["py38"]
include = '\.pyi?$'
exclude = '''
/(
\.git
| \.eggs
| \.idea
| \__pycache__
| venv
| front
| _build
| build
| dist
| migrations
| node_modules
)/
'''
