# Generated by Django 3.2 on 2021-04-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('preffered_shift', models.CharField(choices=[('D', 'Day'), ('N', 'Night')], default=None, max_length=5, null=True)),
                ('preffered_coworkers', models.ManyToManyField(null=True, related_name='_workers_worker_preffered_coworkers_+', to='workers.Worker')),
            ],
        ),
    ]
