# Generated by Django 3.2 on 2021-05-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='shifts',
            field=models.ManyToManyField(to='shifts.Shift'),
        ),
    ]
