# Generated by Django 3.2 on 2021-05-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_shift_first_occurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='duration',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
