name: Test

on: [pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.2
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.2
      - name: Install latest pipenv
        run: python -m pip install pipenv
      - name: Install dependencies
        run: pipenv sync --dev
      - name: Lint with flake8
        run: pipenv run flake8
