name: Test

on: [pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.2
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.2
      - name: Install latest pipenv
        run: python -m pip install pipenv
      - name: Install dependencies
        run: pipenv sync --dev
      - name: Lint with flake8
        run: pipenv run flake8

  black:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.2
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.2
      - name: Install latest pipenv
        run: python -m pip install pipenv
      - name: Install dependencies
        run: pipenv sync --dev
      - name: Check formatting with black
        run: pipenv run black . --check

  isort:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.2
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.2
      - name: Install latest pipenv
        run: python -m pip install pipenv
      - name: Install dependencies
        run: pipenv sync --dev
      - name: Check imports with isort
        run: pipenv run isort . --check

  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: Install dependencies
        run: yarn install
      - name: Lint with eslint
        run: yarn lint
